### ISSUE TITLE
Any error or success message about configuring?

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint_for_vscode#1]
I have configured yayalint in  https://github.com/Taromati2/ghost/commit/9f97cb687d221907c0b2dfa3793648c65d61dff9 as follows:
![png](https://user-images.githubusercontent.com/31927825/178153674-59cc4b06-3fd5-47a3-8f48-fb1a790baa92.png)
![png](https://user-images.githubusercontent.com/31927825/178153686-4f73ab14-e3d2-420a-ba5b-cec4aeb99908.png)

Uh, but what's actually happening is that I don't know how to trigger yayalint to run, and I don't know if there's a problem with the configuration
So I'd like to know if there's a message when there's a problem, and if there's any way to make sure you've got it work.
And lastly, it would be great if the documentation had screenshots or other examples of these configurations, it would really make everything easier.

**Comment by Tatakinov** [comment]
I put the image on [Wiki](https://github.com/Tatakinov/yayalint_for_vscode/wiki).
I hope it is easier to understand.

I think v0.2.0 can tell if lint is working.

**Comment by steve02081504** [comment]
```
Starting yayalint: E:\tools\yayalint\yayalint.exe E:\Microsoft VS Code\master\shiori\aya.txt
Command failed: E:\tools\yayalint\yayalint.exe E:\Microsoft VS Code\master\shiori\aya.txt
Usage: yayalint [-F] [-s] [-w] [-f] [-u] [-d] [-l] [-g] [-h] <path>

Error: too many arguments
```
Looks like a little bit of a problem
1. it is better to add double commas to each path to avoid the command error caused by paths with spaces
  ```diff
  - E:\tools\yayalint\yayalint.exe E:\Microsoft VS Code\master\shiori\aya.txt
  + "E:\tools\yayalint\yayalint.exe" "E:\Microsoft VS Code\master\shiori\aya.txt"
  ```
2. there seems to be a problem with relative paths.

_____

- (PR at #2 )
