### ISSUE TITLE
Chinese localization files are not loaded correctly in js related content

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint_for_vscode#10]
![](https://user-images.githubusercontent.com/31927825/179252373-99e41afd-5deb-4e8e-b353-a1aa5d5591b4.png)
My guess is that the Chinese language is divided into simplified and traditional Chinese so that the content of the local string is not simply `zh`, but `zhc` or `zhs` or something else.
But I'm so ignorant of js that I can't figure out the local string content in my environment in debug, so I can't help at all
![](https://user-images.githubusercontent.com/31927825/179350091-afcadd9f-1083-4caa-88f2-36b92224887c.png)
although the js part is having trouble loading the language resources, the settings-related content is formatted correctly

**Comment by Tatakinov** [comment]
fixed in v0.2.5

**Comment by steve02081504** [comment]
thanks!
