### ISSUE TITLE
reduce the number of lint runs

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint_for_vscode#3]
I observed that lint runs through every time a new dic file is opened, which may not make sense for ghost with its complex dic construction
I'm not sure about vscode's language service architecture, so what I'm thinking may be impractical or difficult to implement
But is it possible to cache the lint information after running it once, so that the lint information can be reused in different dic files?
As well, is it possible to call lint only when the dic file is saved or when there is no current lint information already cached?

**Comment by steve02081504** [comment]
![yayalint](https://user-images.githubusercontent.com/31927825/178541616-e9dda461-b1aa-4c2e-81e2-7fd685dd8aa6.png)
By the way, this is an icon I drew off the top of my head.
Sorry I don't know much about lua and js so I can't help

**Comment by steve02081504** [comment]
- #4

**Comment by Tatakinov** [comment]
Thank you for drawing the icon!

Fixed lint running uselessly when opening files.
