### ISSUE TITLE
Retain lint info after the file editing window is closed

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint_for_vscode#9]
vscode can display the hint level and number in the file tree, but it seems that this information disappears when the corresponding file is closed
Is there any way to keep these?
![a](https://user-images.githubusercontent.com/31927825/179349778-695e07d9-a9b2-4d96-9413-952bd7fd9ec7.gif)

**Comment by Tatakinov** [comment]
Is it better to keep the warnings for a file once opened, or to show all warnings output by lint from the beginning?

**Comment by steve02081504** [comment]
I think it could be changed to output all warnings at the beginning
Perhaps an optional option could be added like the settings to change the strategy for displaying warnings

**Comment by steve02081504** [comment]
fixed in v0.2.6, thanks for this!
